# Generated by Django 3.1.1 on 2020-11-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20201108_0329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
    ]
