# Generated by Django 3.1.1 on 2020-11-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20201113_0221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
