# Generated by Django 3.1.1 on 2020-11-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(),
        ),
    ]
